apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: importer-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: importer
  namespaceSelector:
    matchNames:
      - chuck
  endpoints:
    - port: metrics
      interval: 15s
