# # docker build -t joke-importer:1.0 . --no-cache
FROM python:3.11-slim-buster

RUN apt-get update && apt-get install -y curl libpq-dev gcc

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV POETRY_NO_INTERACTION=1

WORKDIR /code

COPY . /code/

ENV DB_CONNECTION_STRING=

RUN /root/.local/bin/poetry install --no-cache

ENTRYPOINT ["/root/.local/bin/poetry", "run", "python", "importer.py"]
