# docker build -t whitepatrick/joke-importer:1.0 . --no-cache
FROM python:3.11-slim-buster

RUN apt-get update && apt-get install -y curl libpq-dev gcc

ENV POETRY_VERSION=1.3.2

RUN pip install "poetry==$POETRY_VERSION"

ENV POETRY_NO_INTERACTION=1

WORKDIR /code

COPY importer.py pyproject.toml /code/

ENV PYTHONPATH=/code

ENV DB_CONNECTION_STRING=

RUN /usr/local/bin/poetry install --no-root

ENTRYPOINT ["/usr/local/bin/poetry", "run", "python", "importer.py"]
