# # docker build -t joke-reader:1.0 . --no-cache
FROM python:3.11-slim-buster

RUN apt-get update && apt-get install -y curl

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV POETRY_NO_INTERACTION=1

WORKDIR /code

COPY . /code/

ENV DB_LOCATION=/code/chucks_wisdom/sqlite_storage/sqlite.db

RUN /root/.local/bin/poetry install --no-cache

EXPOSE 5000
HEALTHCHECK --interval=30s --timeout=30s --start-period=30s --retries=5 \
            CMD curl -f http://localhost:5000/health || exit 1
ENTRYPOINT ["/root/.local/bin/poetry", "run", "python", "app.py"]
