# docker build -t whitepatrick/joke-reader:1.0 . --no-cache
FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y curl libpq-dev gcc

ENV POETRY_VERSION=1.3.2

RUN pip install "poetry==$POETRY_VERSION"

ENV POETRY_NO_INTERACTION=1

WORKDIR /code

COPY pyproject.toml /code/

ENV PYTHONPATH=/code

ENV DB_CONNECTION_STRING=

RUN /usr/local/bin/poetry install --no-root

COPY reader.py cyberpunk.py tracing.py /code/
COPY templates/ /code/templates/

EXPOSE 5000

ENTRYPOINT ["/usr/local/bin/poetry", "run", "python", "cyberpunk.py"]
