version: '3.8'

services:
  joke-reader:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: joke-reader:1.0
    environment:
      - POETRY_NO_INTERACTION=1
      - DB_LOCATION=/code/chucks_wisdom/sqlite_storage/sqlite.db
    working_dir: /code
    volumes:
      - code-volume:/code
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 30s
    entrypoint: ["/root/.local/bin/poetry", "run", "python", "app.py"]

  joke-importer:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: joke-importer:1.0
    environment:
      - POETRY_NO_INTERACTION=1
      - DB_LOCATION=/code/chucks_wisdom/sqlite_storage/sqlite.db
    working_dir: /code
    volumes:
      - code-volume:/code
    entrypoint: ["/root/.local/bin/poetry", "run", "python", "joke_importer.py"]

volumes:
     code-volume:
