---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: importer
  namespace: chuck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: importer
  template:
    metadata:
      labels:
        app: importer
    spec:
      containers:
        - name: importer
          image: whitepatrick/joke-importer:1.1.0
          imagePullPolicy: Always
          env:
            - name: DB_CONNECTION_STRING
              value: "postgresql://zaphod:zaphod@postgres:5432/chuck"
          ports:
            - containerPort: 5000
