---
apiVersion: batch/v1
kind: Job
metadata:
  name: importer
  namespace: chuck
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: importer
    spec:
      restartPolicy: OnFailure
      containers:
        - name: importer
          image: whitepatrick/joke-importer:1.1.0
          imagePullPolicy: Always
          env:
            - name: DB_CONNECTION_STRING
              value: "postgresql://zaphod:zaphod@postgres:5432/chuck"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
